version: '3.4'

services:
  aspcoremongosample:
    image: ${DOCKER_REGISTRY-}aspcoremongosample
    hostname: aspcoremongosample
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "8085:80"
      - "8086:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    build:
      context: .
      dockerfile: AspCoreMongoSample/Dockerfile
    networks:
      - aspcoremongo

  mongodb:
    image: mongo:latest
    hostname: mongoDatabase
    restart: always
    command: ["--auth"]
    ports:
      - '27017:27017'
    volumes:
      - dbdata6:/data/db
    networks:
      - aspcoremongo

volumes:
  dbdata6:
  
networks:
  aspcoremongo:
    driver: bridge



